# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: who.cr.covid19
canonical: http://www.example.com/fhir/cr/covid19
name: WhoCrCovid19
status: draft
version: 0.1.0
fhirVersion: 4.0.1
# copyright:
copyrightYear: 2020+
releaseLabel: ci-build
title: WHO Case Reporting for COVID-19 Surveillance
description: TODO
# license: CC0-1.0
publisher:
  name: World Health Organization
  url: http://www.example.com
#   email:
# contact:
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001
# experimental: true
dependencies:
  hl7.fhir.us.core: current
#  covid19 : current

# ╭─────────────────────────────────────────────ig.ini─────────────────────────────────────────────╮
# │  To use a provided ig-data/ig.ini file, delete the "template" property below.                  │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
template: who-ig-template

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Table of Contents: toc.html
  Artifacts: artifacts.html

#resources:
#  StructureDefinition/CRSurveillance:
#    name: CR Surveillance
#    description: "TODO too"    
  # StructureDefinition/oncology-AverageCEP17SignalsPerCell-model:
  #   name: oncology-AverageCEP17SignalsPerCell-model
  #   description: "TODO too"    

# ╭───────────────────────────────────────package-list.json────────────────────────────────────────╮
# │  To control the package-list.json using this config, uncomment and set the "history" property. │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
history:
   current: http://www.example.com/fhir/cr/covid19
#   0.10.0:
#     date: 2020-08-31
#     desc: Official v0.10.0 release
#     path: http://www.example.com/fhir/cr/covid19
#     status: draft
#     sequence: Drafts
#     fhirversion: 4.0.1
#     current: true
